image: php:8.3-apache

before_script:
  - apt-get update && apt-get install -y curl git libzip-dev libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev
  - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
  - docker-php-ext-install exif mysqli pdo pdo_mysql zip gd
  - composer install -o

cache:
  paths:
    - vendor/

stages:
  - Validation
  - CodingStandards
  - test

security-checker:
  stage: Validation
  variables:
    PHP_CHECKER_VERSION: 2.0.5
  before_script:
    - curl -o /tmp/security_checker -L "https://github.com/fabpot/local-php-security-checker/releases/download/v${PHP_CHECKER_VERSION}/local-php-security-checker_${PHP_CHECKER_VERSION}_linux_amd64"
    - mv /tmp/security_checker /usr/bin/local-php-security-checker
    - chmod +x /usr/bin/local-php-security-checker
  script:
    - local-php-security-checker --path=./composer.lock
  allow_failure: false

doctrine-schema-validate:
  image: php:8.2-apache
  stage: Validation
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_DATABASE: spaarple
    MYSQL_USER: spaarple
    MYSQL_PASSWORD: spaarple
    DATABASE_URL: 'mysql://root:toor@mysql:3306/spaarple?serverVersion=5.7&charset=utf8mb4'
  before_script:
    - apt-get update && apt-get install -y git libzip-dev libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install exif mysqli pdo pdo_mysql zip gd
    - composer install -o
    - php bin/console doctrine:database:drop --force
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migration:migrate --no-interaction
  script:
    - php bin/console doctrine:schema:validate
  allow_failure: false

twig-lint:
  stage: CodingStandards
  script:
    - php bin/console lint:twig ./templates
  allow_failure: true

