name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: spaarple
          MYSQL_USER: spaarple
          MYSQL_PASSWORD: spaarple
          DATABASE_URL: 'mysql://root:toor@db:3306/spaarple?serverVersion=5.7.43&charset=utf8mb4'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: exif, mysqli, pdo, pdo_mysql, zip, gd
          tools: composer:v2

      - name: Install dependencies
        run: composer install -o

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Security checker
        run: |
          curl -o /tmp/security_checker -L "https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.5/local-php-security-checker_2.0.5_linux_amd64"
          sudo mv /tmp/security_checker /usr/local/bin/local-php-security-checker
          sudo chmod +x /usr/local/bin/local-php-security-checker
          local-php-security-checker --path=./composer.lock

      - name: Doctrine schema validate
        env:
          DATABASE_URL: 'mysql://root:toor@db:3306/spaarple?serverVersion=5.7.43&charset=utf8mb4'
        run: |
          php bin/console doctrine:database:drop --force
          php bin/console doctrine:database:create
          php bin/console doctrine:migration:migrate --no-interaction
          php bin/console doctrine:schema:validate

      - name: Twig lint
        run: php bin/console lint:twig ./templates